name: Nazrah Films
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#777777'
    - '#383838'
    - '#b4b4b4'
    - '#b00515'
  brandStrength: 0.5
  lightness: 0.6218350355047733
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
