name: Nazrah
favicon: null
layout_spectrum: 0.7476058257743716
typography_spectrum: 0.44651937671005726
title: Nazrah Titles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9242158567067236
  lightness: 0.6218350355047733
  saturation: 0.7801366746425629
  rhythmicContrast: 0.02510412852279842
purpose: []
